### ISSUE TITLE
More issues with parsing players

### ISSUE THREAD

**Issue by DavidMente** [PBug90/w3gjs#71]
Similarly to #67 , we have some more failures due to players that cannot be found. I have attached a replay with the issue. This time it's a Netease replay
[moju_vs_fly.zip](https://github.com/PBug90/w3gjs/files/5717096/moju_vs_fly.zip)

**Comment by PBug90** [comment]
Netease appears to use exactly two CommandDataBlocks for metadata. They use an unknown playerId that does not exist as a valid SlotRecord or PlayerRecord. The first CommandDataBlock appears at 66ms of simulation time. The second seems to appear close to or at the end of the replay.

Since its just 2 blocks and they do not refer to playing players, skipping them is an easy to implement option.

**Comment by PBug90** [comment]
Implemented with #72 and published as 2.3.0
