### ISSUE TITLE
Reply file specification

### ISSUE THREAD

**Issue by RMTT** [PBug90/w3gjs#90]
Hello, i find many w3g reply analysis repos, but only this can support nwg and w3g both.
Now i want to using other languages to analysis reply file, maybe there is some specifications of formation of reply file?

**Comment by PBug90** [comment]
If you take a look at nwg files in a hex editor you will find that mostly there is added metadata at the start. Thats why the parser tries to find the correct start offset here: https://github.com/PBug90/w3gjs/blob/master/src/parsers/RawParser.ts#L93

The initial implementation of this repo used http://w3g.deepnode.de/ as spec.

Reforged added some new properties and changed some parser behaviours, but that can be found when looking at the parsers here: https://github.com/PBug90/w3gjs/tree/master/src/parsers

In particular, order of parser application can be found here https://github.com/PBug90/w3gjs/blob/master/src/parsers/ReplayParser.ts#L34

You can also take a look at closed / open issues since a lot of people thankfully contributed with analysing the new reforged metadata added, allowing me or them to add them to this parser.

**Comment by RMTT** [comment]
Thanks very much! This is i want, closed this issue now, thanks again!
